# 端口配置
server:
  port: 8089
  servlet:
    context-path: /bootPlus
    session:
      timeout:
        3000
# spring配置
spring:
  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: E:/upload/temp/
      max-file-size: 100MB
      max-request-size: 100MB
  # 配置jsp
  mvc:
    view:
      prefix: /view/
      suffix: .jsp
    # 静态路径配置
    static-path-pattern: /static/**
  application:
    name: bootPlus
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  # 热部署
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
# mybatis-plus配置
mybatis-plus:
  mapper-locations:
  - classpath:/mapper/*/*Mapper.xml
  type-aliases-package: cn.imp.bootplus.entity
# 日志配置
logging:
  config: classpath:slf4j/logback-boot.xml


